name: TBCPluginV2
main: fun.tbcraft.play.TBCPlugin
description: TBCs Plugin
author: Kilo
version: 1.0.5
api-version: 1.18
softdepend:
  - MythicMobs
  - Alchema
  - WorldGaurd
  - WorldEdit
  - CMI
  - Towny
depend:
  - MythicLib
  - TheAPI
commands:
  tbc:
    description: Main Command
    aliases:
      - TheBetterChoice
      - TBCV2
      - TBC
      - tbcv2
    usage: TBC <Command>
    permission: default
  debugTBC:
    description: Debug Command
    aliases:
      - DebugTBCPlugin
      - DTBC
      - DTBCP
    usage: DTBC Start or DTBC Stop
    permission: default
    permission-message: No Permission for this command. Ask Kilo!
  whereami:
    aliases:
      - where
    usage: Find the world/location of user
    permission-message: No Permission
    permission: default
